// Unicode CLDR supplemental/currencyData, current tender territories (retrieved
// 2026-09-27). The exchange-rate catalogue itself remains Frankfurter-driven.
// Codes without a territory here are supranational, precious-metal, test, or
// otherwise non-territorial currencies and intentionally receive no invented country.
export const CURRENCY_REGIONS = Object.freeze({"SHP":["AC","SH"],"EUR":["AD","AT","AX","BE","BG","BL","CY","DE","EA","EE","ES","EU","FI","FR","GF","GP","GR","HR","IC","IE","IT","LT","LU","LV","MC","ME","MF","MQ","MT","NL","PM","PT","RE","SI","SK","SM","TF","VA","XK","YT"],"AED":["AE"],"AFN":["AF"],"XCD":["AG","AI","DM","GD","KN","LC","MS","VC"],"ALL":["AL"],"AMD":["AM"],"AOA":["AO"],"ARS":["AR"],"USD":["AS","BQ","DG","EC","FM","GU","HT","IO","MH","MP","PA","PR","PW","SV","TC","TL","UM","US","VG","VI","ZW"],"AUD":["AU","CC","CX","HM","KI","NF","NR","TV"],"AWG":["AW"],"AZN":["AZ"],"BAM":["BA"],"BBD":["BB"],"BDT":["BD"],"XOF":["BF","BJ","CI","GW","ML","NE","SN","TG"],"BHD":["BH"],"BIF":["BI"],"BMD":["BM"],"BND":["BN"],"BOB":["BO"],"BRL":["BR"],"BSD":["BS"],"BTN":["BT"],"INR":["BT","IN"],"NOK":["BV","NO","SJ"],"BWP":["BW"],"BYN":["BY"],"BZD":["BZ"],"CAD":["CA"],"CDF":["CD"],"XAF":["CF","CG","CM","GA","GQ","TD"],"CHF":["CH","LI"],"NZD":["CK","NU","NZ","PN","TK"],"CLP":["CL"],"CNY":["CN"],"COP":["CO"],"CRC":["CR"],"CUP":["CU"],"CVE":["CV"],"XCG":["CW","SX"],"CZK":["CZ"],"DJF":["DJ"],"DKK":["DK","FO","GL"],"DOP":["DO"],"DZD":["DZ"],"EGP":["EG"],"MAD":["EH","MA"],"ERN":["ER"],"ETB":["ET"],"FJD":["FJ"],"FKP":["FK"],"GBP":["GB","GG","GS","IM","JE","TA"],"GEL":["GE"],"GHS":["GH"],"GIP":["GI"],"GMD":["GM"],"GNF":["GN"],"GTQ":["GT"],"GYD":["GY"],"HKD":["HK"],"HNL":["HN"],"HTG":["HT"],"HUF":["HU"],"IDR":["ID"],"ILS":["IL","PS"],"IQD":["IQ"],"IRR":["IR"],"ISK":["IS"],"JMD":["JM"],"JOD":["JO","PS"],"JPY":["JP"],"KES":["KE"],"KGS":["KG"],"KHR":["KH"],"KMF":["KM"],"KPW":["KP"],"KRW":["KR"],"KWD":["KW"],"KYD":["KY"],"KZT":["KZ"],"LAK":["LA"],"LBP":["LB"],"LKR":["LK"],"LRD":["LR"],"ZAR":["LS","NA","ZA"],"LSL":["LS"],"LYD":["LY"],"MDL":["MD"],"MGA":["MG"],"MKD":["MK"],"MMK":["MM"],"MNT":["MN"],"MOP":["MO"],"MRU":["MR"],"MUR":["MU"],"MVR":["MV"],"MWK":["MW"],"MXN":["MX"],"MYR":["MY"],"MZN":["MZ"],"NAD":["NA"],"XPF":["NC","PF","WF"],"NGN":["NG"],"NIO":["NI"],"NPR":["NP"],"OMR":["OM"],"PAB":["PA"],"PEN":["PE"],"PGK":["PG"],"PHP":["PH"],"PKR":["PK"],"PLN":["PL"],"PYG":["PY"],"QAR":["QA"],"RON":["RO"],"RSD":["RS"],"RUB":["RU"],"RWF":["RW"],"SAR":["SA"],"SBD":["SB"],"SCR":["SC"],"SDG":["SD"],"SEK":["SE"],"SGD":["SG"],"SLE":["SL"],"SOS":["SO"],"SRD":["SR"],"SSP":["SS"],"STN":["ST"],"SYP":["SY"],"SZL":["SZ"],"THB":["TH"],"TJS":["TJ"],"TMT":["TM"],"TND":["TN"],"TOP":["TO"],"TRY":["TR"],"TTD":["TT"],"TWD":["TW"],"TZS":["TZ"],"UAH":["UA"],"UGX":["UG"],"UYU":["UY"],"UZS":["UZ"],"VES":["VE"],"VND":["VN"],"VUV":["VU"],"WST":["WS"],"YER":["YE"],"ZMW":["ZM"],"ZWG":["ZW"],"ANG":["CW","SX"],"CNH":["CN"],"GGP":["GG"],"IMP":["IM"],"JEP":["JE"],"MRO":["MR"],"SVC":["SV"]});

export const CURRENCY_SPECIAL_REGIONS = Object.freeze({
  CMD: { en: ["COMESA"], zh: ["东南非共同市场"] },
  XDR: { en: ["International Monetary Fund"], zh: ["国际货币基金组织"] },
  XAG: { en: ["Global commodity market"], zh: ["全球大宗商品市场"] },
  XAU: { en: ["Global commodity market"], zh: ["全球大宗商品市场"] },
  XPD: { en: ["Global commodity market"], zh: ["全球大宗商品市场"] },
  XPT: { en: ["Global commodity market"], zh: ["全球大宗商品市场"] }
});
